
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action Action;

	private global::Gtk.Action Action1;

	private global::Gtk.Action Action2;

	private global::Gtk.Fixed fixed1;

	private global::Gtk.VSeparator vseparator2;

	private global::Gtk.Entry entry1;

	private global::Gtk.HSeparator hseparator2;

	private global::Gtk.Label label1;

	private global::Gtk.Label label2;

	private global::Gtk.Label label3;

	private global::Gtk.Label label4;

	private global::Gtk.Label label5;

	private global::Gtk.Label label6;

	private global::Gtk.Label label7;

	private global::Gtk.Label label8;

	private global::Gtk.Label label9;

	private global::Gtk.Label label10;

	private global::Gtk.Label label11;

	private global::Gtk.Label label12;

	private global::Gtk.Label label13;

	private global::Gtk.Label label14;

	private global::Gtk.Label label15;

	private global::Gtk.Label label16;

	private global::Gtk.Label label17;

	private global::Gtk.VScrollbar persoonbar;

	private global::Gtk.Button button1;

	private global::Gtk.Button button2;

	private global::Gtk.Button button3;

	private global::Gtk.Button button4;

	private global::Gtk.Button button5;

	private global::Gtk.Button button6;

	private global::Gtk.Button button7;

	private global::Gtk.Button button8;

	private global::Gtk.Button button9;

	private global::Gtk.Button button10;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.Action = new global::Gtk.Action("Action", null, null, null);
		w1.Add(this.Action, null);
		this.Action1 = new global::Gtk.Action("Action1", null, null, null);
		w1.Add(this.Action1, null);
		this.Action2 = new global::Gtk.Action("Action2", null, null, null);
		w1.Add(this.Action2, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.WidthRequest = 20;
		this.fixed1.HeightRequest = 20;
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.vseparator2 = new global::Gtk.VSeparator();
		this.vseparator2.HeightRequest = 800;
		this.vseparator2.Name = "vseparator2";
		this.fixed1.Add(this.vseparator2);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.vseparator2]));
		w2.X = 766;
		w2.Y = 7;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entry1 = new global::Gtk.Entry();
		this.entry1.WidthRequest = 600;
		this.entry1.HeightRequest = 40;
		this.entry1.CanFocus = true;
		this.entry1.ExtensionEvents = ((global::Gdk.ExtensionMode)(1));
		this.entry1.Name = "entry1";
		this.entry1.IsEditable = true;
		this.entry1.ActivatesDefault = true;
		this.entry1.InvisibleChar = '•';
		this.fixed1.Add(this.entry1);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.entry1]));
		w3.X = 10;
		w3.Y = 432;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.hseparator2 = new global::Gtk.HSeparator();
		this.hseparator2.WidthRequest = 700;
		this.hseparator2.Name = "hseparator2";
		this.fixed1.Add(this.hseparator2);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.hseparator2]));
		w4.X = -28;
		w4.Y = 418;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.fixed1.Add(this.label1);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label1]));
		w5.X = 5;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.fixed1.Add(this.label2);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label2]));
		w6.Y = 25;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.fixed1.Add(this.label3);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label3]));
		w7.Y = 50;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label4 = new global::Gtk.Label();
		this.label4.Name = "label4";
		this.fixed1.Add(this.label4);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label4]));
		w8.Y = 75;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label5 = new global::Gtk.Label();
		this.label5.Name = "label5";
		this.fixed1.Add(this.label5);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label5]));
		w9.Y = 100;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label6 = new global::Gtk.Label();
		this.label6.Name = "label6";
		this.fixed1.Add(this.label6);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label6]));
		w10.Y = 125;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label7 = new global::Gtk.Label();
		this.label7.Name = "label7";
		this.fixed1.Add(this.label7);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label7]));
		w11.Y = 150;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label8 = new global::Gtk.Label();
		this.label8.Name = "label8";
		this.fixed1.Add(this.label8);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label8]));
		w12.Y = 175;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label9 = new global::Gtk.Label();
		this.label9.Name = "label9";
		this.fixed1.Add(this.label9);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label9]));
		w13.Y = 200;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label10 = new global::Gtk.Label();
		this.label10.Name = "label10";
		this.fixed1.Add(this.label10);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label10]));
		w14.Y = 225;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label11 = new global::Gtk.Label();
		this.label11.Name = "label11";
		this.fixed1.Add(this.label11);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label11]));
		w15.X = -6;
		w15.Y = 249;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label12 = new global::Gtk.Label();
		this.label12.Name = "label12";
		this.fixed1.Add(this.label12);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label12]));
		w16.Y = 275;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label13 = new global::Gtk.Label();
		this.label13.Name = "label13";
		this.fixed1.Add(this.label13);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label13]));
		w17.Y = 300;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label14 = new global::Gtk.Label();
		this.label14.Name = "label14";
		this.fixed1.Add(this.label14);
		global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label14]));
		w18.Y = 325;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label15 = new global::Gtk.Label();
		this.label15.Name = "label15";
		this.fixed1.Add(this.label15);
		global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label15]));
		w19.Y = 350;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label16 = new global::Gtk.Label();
		this.label16.Name = "label16";
		this.fixed1.Add(this.label16);
		global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label16]));
		w20.Y = 375;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label17 = new global::Gtk.Label();
		this.label17.Name = "label17";
		this.fixed1.Add(this.label17);
		global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label17]));
		w21.Y = 400;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.persoonbar = new global::Gtk.VScrollbar(null);
		this.persoonbar.HeightRequest = 400;
		this.persoonbar.Name = "persoonbar";
		this.persoonbar.Adjustment.Lower = 1D;
		this.persoonbar.Adjustment.Upper = 92D;
		this.persoonbar.Adjustment.PageIncrement = 1D;
		this.persoonbar.Adjustment.PageSize = 1D;
		this.persoonbar.Adjustment.StepIncrement = 1D;
		this.persoonbar.Adjustment.Value = 1D;
		this.fixed1.Add(this.persoonbar);
		global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.persoonbar]));
		w22.X = 590;
		w22.Y = 9;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button1 = new global::Gtk.Button();
		this.button1.WidthRequest = 85;
		this.button1.HeightRequest = 30;
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.fixed1.Add(this.button1);
		global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button1]));
		w23.X = 500;
		w23.Y = 10;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button2 = new global::Gtk.Button();
		this.button2.WidthRequest = 85;
		this.button2.HeightRequest = 30;
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.fixed1.Add(this.button2);
		global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button2]));
		w24.X = 500;
		w24.Y = 50;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button3 = new global::Gtk.Button();
		this.button3.WidthRequest = 85;
		this.button3.HeightRequest = 30;
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.fixed1.Add(this.button3);
		global::Gtk.Fixed.FixedChild w25 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button3]));
		w25.X = 500;
		w25.Y = 90;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button4 = new global::Gtk.Button();
		this.button4.WidthRequest = 85;
		this.button4.HeightRequest = 30;
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.fixed1.Add(this.button4);
		global::Gtk.Fixed.FixedChild w26 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button4]));
		w26.X = 500;
		w26.Y = 130;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button5 = new global::Gtk.Button();
		this.button5.WidthRequest = 85;
		this.button5.HeightRequest = 30;
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.fixed1.Add(this.button5);
		global::Gtk.Fixed.FixedChild w27 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button5]));
		w27.X = 500;
		w27.Y = 170;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button6 = new global::Gtk.Button();
		this.button6.WidthRequest = 85;
		this.button6.HeightRequest = 30;
		this.button6.CanFocus = true;
		this.button6.Name = "button6";
		this.button6.UseUnderline = true;
		this.fixed1.Add(this.button6);
		global::Gtk.Fixed.FixedChild w28 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button6]));
		w28.X = 500;
		w28.Y = 210;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button7 = new global::Gtk.Button();
		this.button7.WidthRequest = 85;
		this.button7.HeightRequest = 30;
		this.button7.CanFocus = true;
		this.button7.Name = "button7";
		this.button7.UseUnderline = true;
		this.fixed1.Add(this.button7);
		global::Gtk.Fixed.FixedChild w29 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button7]));
		w29.X = 500;
		w29.Y = 250;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button8 = new global::Gtk.Button();
		this.button8.WidthRequest = 85;
		this.button8.HeightRequest = 30;
		this.button8.CanFocus = true;
		this.button8.Name = "button8";
		this.button8.UseUnderline = true;
		this.fixed1.Add(this.button8);
		global::Gtk.Fixed.FixedChild w30 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button8]));
		w30.X = 500;
		w30.Y = 290;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button9 = new global::Gtk.Button();
		this.button9.WidthRequest = 85;
		this.button9.HeightRequest = 30;
		this.button9.CanFocus = true;
		this.button9.Name = "button9";
		this.button9.UseUnderline = true;
		this.fixed1.Add(this.button9);
		global::Gtk.Fixed.FixedChild w31 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button9]));
		w31.X = 500;
		w31.Y = 330;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button10 = new global::Gtk.Button();
		this.button10.WidthRequest = 85;
		this.button10.HeightRequest = 30;
		this.button10.CanFocus = true;
		this.button10.Name = "button10";
		this.button10.UseUnderline = true;
		this.fixed1.Add(this.button10);
		global::Gtk.Fixed.FixedChild w32 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button10]));
		w32.X = 500;
		w32.Y = 370;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 616;
		this.DefaultHeight = 481;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.entry1.Activated += new global::System.EventHandler(this.sendmessages);
		this.persoonbar.ChangeValue += new global::Gtk.ChangeValueHandler(this.scroll);
		this.button1.Clicked += new global::System.EventHandler(this.user1);
		this.button3.Clicked += new global::System.EventHandler(this.user3);
		this.button4.Clicked += new global::System.EventHandler(this.user4);
		this.button5.Clicked += new global::System.EventHandler(this.user5);
		this.button6.Clicked += new global::System.EventHandler(this.user6);
		this.button7.Clicked += new global::System.EventHandler(this.user7);
		this.button8.Clicked += new global::System.EventHandler(this.user8);
		this.button9.Clicked += new global::System.EventHandler(this.user9);
		this.button10.Clicked += new global::System.EventHandler(this.user10);
	}
}
